// <auto-generated />
using System;
using Marketio_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marketio_Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206164806_UpdateSeedDataTo4ProductsPerCategory")]
    partial class UpdateSeedDataTo4ProductsPerCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marketio_Shared.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Marketio_Shared.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Marketio_Shared.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Marketio_Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5525),
                            Description = "Krachtige laptop met 16GB RAM en 512GB SSD",
                            ImageUrl = "/images/laptop.jpg",
                            IsActive = true,
                            Name = "Laptop Dell XPS 15",
                            Price = 1299.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5538),
                            Description = "Nieuwste iPhone met A17 Pro chip",
                            ImageUrl = "/images/iphone.jpg",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 1099.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5542),
                            Description = "Crystal UHD 4K Smart TV",
                            ImageUrl = "/images/tv.jpg",
                            IsActive = true,
                            Name = "Samsung 4K TV 55\"",
                            Price = 699.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5546),
                            Description = "Noise cancelling koptelefoon",
                            ImageUrl = "/images/headphones.jpg",
                            IsActive = true,
                            Name = "Sony WH-1000XM5",
                            Price = 349.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5550),
                            Description = "Comfortabele sportschoenen",
                            ImageUrl = "/images/sneakers.jpg",
                            IsActive = true,
                            Name = "Nike Air Max Sneakers",
                            Price = 129.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5557),
                            Description = "Klassieke straight fit jeans",
                            ImageUrl = "/images/jeans.jpg",
                            IsActive = true,
                            Name = "Levi's 501 Jeans",
                            Price = 89.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5560),
                            Description = "Warme hoodie met logo",
                            ImageUrl = "/images/hoodie.jpg",
                            IsActive = true,
                            Name = "Adidas Hoodie",
                            Price = 59.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5564),
                            Description = "Katoenen polo shirt",
                            ImageUrl = "/images/polo.jpg",
                            IsActive = true,
                            Name = "Tommy Hilfiger Polo",
                            Price = 69.99m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5568),
                            Description = "Handbook of Agile Software Craftsmanship",
                            ImageUrl = "/images/cleancode.jpg",
                            IsActive = true,
                            Name = "Clean Code - Robert Martin",
                            Price = 39.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 12,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5573),
                            Description = "From Journeyman to Master",
                            ImageUrl = "/images/pragmatic.jpg",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 44.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5577),
                            Description = "Elements of Reusable Object-Oriented Software",
                            ImageUrl = "/images/patterns.jpg",
                            IsActive = true,
                            Name = "Design Patterns",
                            Price = 49.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5581),
                            Description = "Complete serie van 7 boeken",
                            ImageUrl = "/images/harrypotter.jpg",
                            IsActive = true,
                            Name = "Harry Potter Box Set",
                            Price = 89.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 16,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5584),
                            Description = "Draadloze stofzuiger met laser",
                            ImageUrl = "/images/vacuum.jpg",
                            IsActive = true,
                            Name = "Dyson V15 Stofzuiger",
                            Price = 599.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 17,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5588),
                            Description = "Hetelucht friteuse 7.3L",
                            ImageUrl = "/images/airfryer.jpg",
                            IsActive = true,
                            Name = "Philips Airfryer XXL",
                            Price = 249.99m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 18,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5592),
                            Description = "Verstelbaar bureau 160x80cm",
                            ImageUrl = "/images/desk.jpg",
                            IsActive = true,
                            Name = "IKEA Bureau BEKANT",
                            Price = 349.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 19,
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5595),
                            Description = "Koffiemachine met melkopschuimer",
                            ImageUrl = "/images/nespresso.jpg",
                            IsActive = true,
                            Name = "Nespresso Machine",
                            Price = 199.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 21,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5599),
                            Description = "Extra dikke yoga mat 6mm",
                            ImageUrl = "/images/yogamat.jpg",
                            IsActive = true,
                            Name = "Yoga Mat Premium",
                            Price = 39.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 22,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5604),
                            Description = "Verstelbare dumbbell set",
                            ImageUrl = "/images/dumbbells.jpg",
                            IsActive = true,
                            Name = "Dumbbells Set 20kg",
                            Price = 149.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 23,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5608),
                            Description = "GPS hardloop smartwatch",
                            ImageUrl = "/images/garmin.jpg",
                            IsActive = true,
                            Name = "Garmin Forerunner 265",
                            Price = 449.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 24,
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 6, 16, 48, 5, 481, DateTimeKind.Utc).AddTicks(5611),
                            Description = "Officiële wedstrijdbal",
                            ImageUrl = "/images/football.jpg",
                            IsActive = true,
                            Name = "Voetbal Nike Strike",
                            Price = 29.99m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Marketio_Shared.Entities.OrderItem", b =>
                {
                    b.HasOne("Marketio_Shared.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketio_Shared.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketio_Shared.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Marketio_Shared.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
